### ISSUE TITLE
Could you please fix Tran_Opamp.py example

### ISSUE THREAD

**Issue by beta68** [victorpreuss/YalRF#2]
I get this error message:

```
Traceback (most recent call last):
  File "/Users/rudi/Desktop/YalRF/yalrf/Tran_Opamp.py", line 19, in <module>
    y.run('AC1')
  File "/Users/rudi/Desktop/YalRF/yalrf/YalRF.py", line 152, in run
    sol = self.analyses[name].run(self, x0, nodeset)
  File "/Users/rudi/Desktop/YalRF/yalrf/Analyses/AC.py", line 75, in run
    dev.calc_oppoint(self.xdc, False)
TypeError: Opamp.calc_oppoint() takes 2 positional arguments but 3 were given
```

Thank you very much for taking a look.

**Comment by victorpreuss** [comment]
See if it works now

**Comment by victorpreuss** [comment]
It seems to work now, although I don't remember what the TB does exactly. There are many TBs that might be outdated as I've changed the interfaces many times. The HarmonicBalance class is not working anymore, only MultiToneHarmonicBalance, which can be used with a single input tone

**Comment by beta68** [comment]
Now all is perfectly fine. Thank you so much, Victor.

**Comment by victorpreuss** [comment]
no worries, please let me know if you find any more issues (there are probably a good amount)
