### ISSUE TITLE
S-parameter example

### ISSUE THREAD

**Issue by beta68** [victorpreuss/YalRF#3]
Hello Victor,

This is not an issue. Could you do me a favor and provide a small example on how S-parameters can be calculated using AC analysis, e.g. for the BJT, please?

Thank you for considering.

**Comment by beta68** [comment]
I found out in the meantime. You can add bias T at gate and drain. Add a AC vsource at gate to 50 Ohm. s21 = vac, s11=vac-1. You can do the same at output for s22 and s12. This "issue" can be closed. Thank you.

**Comment by victorpreuss** [comment]
Hey, sorry for the delay, but yes, your approach is correct. You can just start from the basic definitions of s-parameters (place 50 ohm ports and measuring the waves)
